# Site
name: "Keywords for Caribbean Studies"
title: "Keywords"
description: "Digital sources for teaching Caribbean studies"
favicon: 'assets/images/logo.png'
baseurl: /keywords
include: ["_pages"]
permalink: pretty

# Authors
authors:
  kelly:
    name: Kelly Baker Josephs
    email: kbjosephs@gmail.com
    twitter: https://twitter.com/kbjosephs

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
